"""DRS disclosure extraction (#844 PR-2): normalizer, corpus-fixture
extraction table, quantity parsing, and the observation write/read path."""

from __future__ import annotations

from datetime import date
from decimal import Decimal
from pathlib import Path

import psycopg
import pytest

from app.services.drs_disclosure import (
    DrsDisclosure,
    _parse_quantity,
    extract_drs_disclosure,
    normalize_filing_text,
    refresh_drs_disclosures,
)
from app.services.ownership_rollup import _read_drs

_FIX = Path(__file__).parent / "fixtures" / "drs"

# --- normalize_filing_text ------------------------------------------------------


def test_normalizer_heals_ixbrl_word_fragmentation() -> None:
    # Inline tags mid-word must strip to '' (a space would fragment the
    # word — the "approxim ately" corpus landmine); block tags space-join.
    html = (
        '<div>approxim<span style="x">ately</span> 66.2 million '
        'sh<ix:nonNumeric name="y">ares</ix:nonNumeric></div><p>next</p>'
    )
    assert normalize_filing_text(html) == " approximately 66.2 million shares next "


def test_normalizer_maps_entities() -> None:
    assert normalize_filing_text("Cede &amp; Co&#160;(&#8220;DTC&#8221;)") == 'Cede & Co ("DTC")'


# --- _parse_quantity ------------------------------------------------------------


@pytest.mark.parametrize(
    ("num", "unit", "expected"),
    [
        ("382.4", "million", Decimal("382400000.0")),
        ("1.2", "billion", Decimal("1200000000.0")),
        ("529,547,465", None, Decimal("529547465")),
        # AMC's missing-"million" shape: bare small decimal scales ×1e6.
        ("527.5", None, Decimal("527500000.0")),
        # A real absolute count above the 10k floor stays literal.
        ("14,021", None, Decimal("14021")),
    ],
)
def test_parse_quantity(num: str, unit: str | None, expected: Decimal) -> None:
    assert _parse_quantity(num, unit) == expected


# --- extraction over the corpus fixtures ----------------------------------------
#
# Expected values pin the 2026-07-23 full-corpus run (18/18 disclosing hits,
# 0 false positives over 9 non-disclosing era filings). Fixtures are
# normalized ±1500-char windows around the anchor (or a head slice for
# non-disclosers), generated by the corpus script from the raw EDGAR docs.

_EXPECTED: dict[str, tuple[Decimal, Decimal | None] | None] = {
    # fixture → (registered_shares, street_shares) or None for no-disclosure
    "gme_10k_2023-03-28.txt": (Decimal("76000000.0"), Decimal("228700000.0")),
    "gme_10q_2023-06-07.txt": (Decimal("76600000.0"), Decimal("228100000.0")),
    "gme_10k_2024-03-26.txt": (Decimal("75300000.0"), Decimal("230600000.0")),
    "gme_10kaa_2024-03-27.txt": (Decimal("75300000.0"), Decimal("230600000.0")),
    "gme_10q_2024-09-10.txt": (Decimal("72800000.0"), Decimal("353700000.0")),
    "gme_10k_2025-03-25.txt": (Decimal("69500000.0"), Decimal("377600000.0")),
    # iXBRL-fragmented era (the "approxim ately" shape)
    "gme_10q_2025-09-09.txt": (Decimal("66700000.0"), Decimal("381000000.0")),
    "gme_10k_2026-03-24.txt": (Decimal("66200000.0"), Decimal("382400000.0")),
    "gme_10q_2026-06-11.txt": (Decimal("65000000.0"), Decimal("383700000.0")),
    "amc_10q_2025-11-05.txt": (Decimal("1800000.0"), Decimal("511100000.0")),
    "amc_10k_2026-02-23.txt": (Decimal("2000000.0"), Decimal("527500000.0")),
    "amc_10q_2026-05-05.txt": (Decimal("2700000.0"), Decimal("602500000.0")),
    # Non-disclosing: pre-era 10-Qs / 10-Ks and Part-III 10-K/As.
    "gme_10q_2022-09-07.txt": None,
    "amc_10k_2024-02-28.txt": None,
    "amc_10k_2025-02-26.txt": None,
    "amc_10kaa_2026-04-30.txt": None,
    "amc_10q_2025-08-11.txt": None,
}


@pytest.mark.parametrize("fixture", sorted(_EXPECTED))
def test_extract_corpus_fixture(fixture: str) -> None:
    text = (_FIX / fixture).read_text()
    got = extract_drs_disclosure(text)
    expected = _EXPECTED[fixture]
    if expected is None:
        assert got is None
    else:
        assert got is not None
        assert (got.registered_shares, got.street_shares) == expected


def test_extract_gme_2026_10k_full_fields() -> None:
    got = extract_drs_disclosure((_FIX / "gme_10k_2026-03-24.txt").read_text())
    assert got == DrsDisclosure(
        registered_shares=Decimal("66200000.0"),
        registered_pct=Decimal("15"),
        street_shares=Decimal("382400000.0"),
        street_pct=Decimal("85"),
        holders_of_record=177522,
        as_of_date=date(2026, 3, 18),
    )


def test_record_holders_count_sentence_alone_is_not_a_disclosure() -> None:
    # The mandated Item 201(b) sentence with no split context must not
    # anchor an extraction (guard for the record-holders anchor variant).
    text = (
        "As of March 22, 2023, there were 197,058 record holders of our Class A "
        "Common Stock. Dividends were held by record holders of record."
    )
    assert extract_drs_disclosure(text) is None


def test_cross_side_sanity_rejects_inconsistent_pcts() -> None:
    text = (
        "approximately 10.0 million shares (50%) were held by registered holders "
        "with our transfer agent and approximately 90.0 million shares (50%) were "
        "held by Cede & Co."
    )
    assert extract_drs_disclosure(text) is None


# --- DB: refresh (frontier + fake provider) + read path -------------------------

_NEXT_IID = [918600]


def _seed_instrument(conn: psycopg.Connection[tuple], *, symbol: str, cik: str) -> int:
    _NEXT_IID[0] += 1
    iid = _NEXT_IID[0]
    with conn.cursor() as cur:
        cur.execute(
            "INSERT INTO instruments (instrument_id, symbol, company_name, currency, is_tradable) "
            "VALUES (%s, %s, %s, 'USD', TRUE)",
            (iid, symbol, f"{symbol} Inc."),
        )
        cur.execute(
            "INSERT INTO external_identifiers (instrument_id, provider, identifier_type, identifier_value, is_primary) "
            "VALUES (%s, 'sec', 'cik', %s, TRUE)",
            (iid, cik),
        )
    conn.commit()
    return iid


class _FakeProvider:
    def __init__(self, bodies: dict[str, str]) -> None:
        self.bodies = bodies
        self.fetched: list[str] = []

    def fetch_document_text(self, absolute_url: str) -> str | None:
        self.fetched.append(absolute_url)
        return self.bodies.get(absolute_url)


@pytest.mark.db
class TestDrsRefresh:
    def test_frontier_refresh_and_read(self, ebull_test_conn: psycopg.Connection[tuple], tmp_path: Path) -> None:
        iid = _seed_instrument(ebull_test_conn, symbol="DRSX", cik="0001326380")
        disclosing = (_FIX / "gme_10k_2026-03-24.txt").read_text()
        with ebull_test_conn.cursor() as cur:
            cur.execute(
                """
                INSERT INTO sec_filing_manifest (accession_number, cik, form, source, subject_type,
                    subject_id, instrument_id, filed_at, primary_document_url, ingest_status)
                VALUES ('drs-acc-1', '0001326380', '10-K', 'sec_10k', 'issuer', %(iid)s, %(iid)s,
                        '2026-03-24T12:00:00Z', 'https://x/one', 'parsed'),
                       ('drs-acc-0', '0001326380', '10-Q', 'sec_10q', 'issuer', %(iid)s, %(iid)s,
                        '2025-12-09T12:00:00Z', 'https://x/zero', 'parsed')
                """,
                {"iid": iid},
            )
        ebull_test_conn.commit()

        provider = _FakeProvider({"https://x/one": disclosing, "https://x/zero": "no split here"})
        result = refresh_drs_disclosures(ebull_test_conn, provider)
        assert result.filings_examined == 2
        assert result.filings_extracted == 1
        assert result.filings_no_disclosure == 1

        info = _read_drs(ebull_test_conn, iid, today=date(2026, 7, 23))
        assert info is not None
        assert info.registered_shares == Decimal("66200000.0")
        assert info.holders_of_record == 177522
        assert info.as_of_date == date(2026, 3, 18)

        # Staleness: >400 days after the as-of → suppressed.
        assert _read_drs(ebull_test_conn, iid, today=date(2027, 6, 1)) is None

        # Frontier: second run examines nothing (no filings newer than the
        # newest stored observation's filed_at).
        provider2 = _FakeProvider({})
        result2 = refresh_drs_disclosures(ebull_test_conn, provider2)
        assert result2.filings_examined == 0
        assert provider2.fetched == []
