/**
 * /reports — weekly + monthly report snapshots.
 *
 * Surfaces data already generated by the weekly_report + monthly_report
 * jobs. Lets the operator decide whether the reports justify keeping
 * the jobs scheduled (Phase 1.4 retirement decision) — if nobody opens
 * this page after two cycles, retiring is safe.
 */

import { useEffect, useState } from "react";
import { Link } from "react-router-dom";

import { fetchMonthlyReports, fetchWeeklyReports } from "@/api/reports";
import type { ReportSnapshot } from "@/api/reports";
import { Section, SectionSkeleton } from "@/components/dashboard/Section";
import { EmptyState } from "@/components/states/EmptyState";
import { useAsync } from "@/lib/useAsync";

interface ContributorRow {
  instrument_id: number;
  symbol: string;
  pnl_delta: string | null;
  pnl_pct: string | null;
}

function formatSignedPnl(raw: string | null | undefined): string {
  if (raw === null || raw === undefined) return "—";
  const num = Number(raw);
  if (!Number.isFinite(num)) return "—";
  const sign = num > 0 ? "+" : "";
  return `${sign}${num.toLocaleString(undefined, {
    style: "currency",
    currency: "USD",
    maximumFractionDigits: 0,
  })}`;
}

function formatSignedPct(raw: string | null | undefined): string {
  if (raw === null || raw === undefined) return "—";
  const num = Number(raw);
  if (!Number.isFinite(num)) return "—";
  const sign = num > 0 ? "+" : "";
  return `${sign}${(num * 100).toFixed(2)}%`;
}

type TabId = "weekly" | "monthly";

function ErrorView({ error }: { error: unknown }) {
  const message = error instanceof Error ? error.message : "Request failed.";
  return (
    <div className="rounded border border-red-200 bg-red-50 p-3 text-sm text-red-700">
      {message}
    </div>
  );
}

function formatDate(iso: string | null | undefined): string {
  if (!iso) return "—";
  const head = iso.slice(0, 10);
  // ISO date-prefix like "2026-04-19" — anything shorter or malformed
  // falls back to the em-dash sentinel used elsewhere on the page.
  if (!/^\d{4}-\d{2}-\d{2}$/.test(head)) return "—";
  return head;
}

function formatMoney(raw: unknown): string {
  if (raw === null || raw === undefined) return "—";
  const num = Number(raw);
  if (!Number.isFinite(num)) return "—";
  return num.toLocaleString(undefined, {
    style: "currency",
    currency: "USD",
    maximumFractionDigits: 0,
  });
}

function formatPct(raw: unknown): string {
  if (raw === null || raw === undefined) return "—";
  const num = Number(raw);
  if (!Number.isFinite(num)) return "—";
  return `${num.toFixed(2)}%`;
}

/**
 * Render a single report snapshot. Snapshot schemas differ between weekly
 * and monthly — we key off `report_type` and fall back to a raw JSON
 * dump for any section we don't yet recognise.
 */
function ReportDetail({ report }: { report: ReportSnapshot }) {
  const json = report.snapshot_json;
  const reportType = report.report_type;

  const pnl = json["pnl"] as Record<string, unknown> | undefined;
  const topPerformers = json["top_performers"] as
    | Array<Record<string, unknown>>
    | undefined;
  const bottomPerformers = json["bottom_performers"] as
    | Array<Record<string, unknown>>
    | undefined;
  const upcomingEarnings = json["upcoming_earnings"] as
    | Array<Record<string, unknown>>
    | undefined;
  const winRate = json["win_rate"] as number | undefined;
  const avgHoldingDays = json["avg_holding_days"] as number | undefined;
  const bestTrade = json["best_trade"] as Record<string, unknown> | null | undefined;
  const worstTrade = json["worst_trade"] as Record<string, unknown> | null | undefined;
  const thesisAccuracy = json["thesis_accuracy"] as
    | Record<string, unknown>
    | undefined;
  // Slice 4 of per-stock research page spec: top contributors /
  // drags vs the prior snapshot, each row linking to the research
  // page so the Reports view becomes an entry point into per-stock
  // analysis rather than a terminal JSON dump.
  const periodContribution = json["period_contribution"] as
    | { contributors?: ContributorRow[]; drags?: ContributorRow[] }
    | undefined;
  const contributors = periodContribution?.contributors ?? [];
  const drags = periodContribution?.drags ?? [];

  return (
    <div className="space-y-4">
      <div className="flex items-baseline gap-3 text-sm">
        <span className="font-medium">
          {formatDate(report.period_start)} → {formatDate(report.period_end)}
        </span>
        <span className="text-xs text-slate-500">
          generated {formatDate(report.computed_at)}
        </span>
      </div>

      {pnl && (
        <div>
          <h3 className="mb-1 text-xs font-medium uppercase tracking-wide text-slate-500">
            P&amp;L
          </h3>
          <dl className="grid grid-cols-2 gap-y-1 text-sm md:grid-cols-4">
            <dt className="text-slate-500">Realised</dt>
            <dd>{formatMoney(pnl["realised_pnl"])}</dd>
            <dt className="text-slate-500">Unrealised</dt>
            <dd>{formatMoney(pnl["unrealised_pnl"])}</dd>
            <dt className="text-slate-500">Portfolio value</dt>
            <dd>{formatMoney(pnl["portfolio_value"])}</dd>
            <dt className="text-slate-500">Cash</dt>
            <dd>{formatMoney(pnl["cash"])}</dd>
          </dl>
        </div>
      )}

      {reportType === "monthly" && (winRate !== undefined || avgHoldingDays !== undefined) && (
        <div>
          <h3 className="mb-1 text-xs font-medium uppercase tracking-wide text-slate-500">
            Trade stats
          </h3>
          <dl className="grid grid-cols-2 gap-y-1 text-sm md:grid-cols-4">
            <dt className="text-slate-500">Win rate</dt>
            <dd>{formatPct(winRate)}</dd>
            <dt className="text-slate-500">Avg holding (days)</dt>
            <dd>{avgHoldingDays !== undefined ? String(avgHoldingDays) : "—"}</dd>
          </dl>
        </div>
      )}

      {(contributors.length > 0 || drags.length > 0) && (
        <div>
          <h3 className="mb-1 text-xs font-medium uppercase tracking-wide text-slate-500">
            Period contribution (vs prior snapshot)
          </h3>
          <div className="grid gap-4 md:grid-cols-2">
            <div>
              <div className="mb-1 text-[11px] font-semibold uppercase text-emerald-700">
                Top contributors
              </div>
              <ContributorList rows={contributors} tone="positive" />
            </div>
            <div>
              <div className="mb-1 text-[11px] font-semibold uppercase text-red-700">
                Top drags
              </div>
              <ContributorList rows={drags} tone="negative" />
            </div>
          </div>
        </div>
      )}

      {topPerformers && topPerformers.length > 0 && (
        <div>
          <h3 className="mb-1 text-xs font-medium uppercase tracking-wide text-slate-500">
            Top performers
          </h3>
          <ul className="space-y-1 text-sm">
            {topPerformers.map((p, idx) => (
              <li key={idx}>
                <span className="font-medium">{String(p["symbol"] ?? "?")}</span>{" "}
                <span className="text-slate-500">{formatPct(p["return_pct"])}</span>
              </li>
            ))}
          </ul>
        </div>
      )}

      {bottomPerformers && bottomPerformers.length > 0 && (
        <div>
          <h3 className="mb-1 text-xs font-medium uppercase tracking-wide text-slate-500">
            Bottom performers
          </h3>
          <ul className="space-y-1 text-sm">
            {bottomPerformers.map((p, idx) => (
              <li key={idx}>
                <span className="font-medium">{String(p["symbol"] ?? "?")}</span>{" "}
                <span className="text-slate-500">{formatPct(p["return_pct"])}</span>
              </li>
            ))}
          </ul>
        </div>
      )}

      {reportType === "monthly" && (bestTrade || worstTrade) && (
        <div>
          <h3 className="mb-1 text-xs font-medium uppercase tracking-wide text-slate-500">
            Best / worst trade
          </h3>
          {bestTrade && (
            <p className="text-sm">
              Best: <span className="font-medium">{String(bestTrade["symbol"] ?? "?")}</span>{" "}
              <span className="text-emerald-600">{formatPct(bestTrade["return_pct"])}</span>
            </p>
          )}
          {worstTrade && (
            <p className="text-sm">
              Worst: <span className="font-medium">{String(worstTrade["symbol"] ?? "?")}</span>{" "}
              <span className="text-red-600">{formatPct(worstTrade["return_pct"])}</span>
            </p>
          )}
        </div>
      )}

      {reportType === "monthly" && thesisAccuracy && (
        <div>
          <h3 className="mb-1 text-xs font-medium uppercase tracking-wide text-slate-500">
            Thesis accuracy
          </h3>
          <dl className="grid grid-cols-2 gap-y-1 text-sm">
            <dt className="text-slate-500">Buy theses that worked</dt>
            <dd>{formatPct(thesisAccuracy["buy_hit_rate_pct"])}</dd>
            <dt className="text-slate-500">Avoid theses that worked</dt>
            <dd>{formatPct(thesisAccuracy["avoid_hit_rate_pct"])}</dd>
          </dl>
        </div>
      )}

      {upcomingEarnings && upcomingEarnings.length > 0 && (
        <div>
          <h3 className="mb-1 text-xs font-medium uppercase tracking-wide text-slate-500">
            Upcoming earnings
          </h3>
          <ul className="space-y-1 text-sm">
            {upcomingEarnings.map((e, idx) => (
              <li key={idx}>
                <span className="font-medium">{String(e["symbol"] ?? "?")}</span>{" "}
                <span className="text-slate-500">{formatDate(String(e["earnings_date"] ?? ""))}</span>
              </li>
            ))}
          </ul>
        </div>
      )}

      <details className="text-xs">
        <summary className="cursor-pointer text-slate-500">Raw JSON</summary>
        <pre className="mt-2 overflow-x-auto rounded bg-slate-50 p-2">
          {JSON.stringify(json, null, 2)}
        </pre>
      </details>
    </div>
  );
}

function ContributorList({
  rows,
  tone,
}: {
  rows: ContributorRow[];
  tone: "positive" | "negative";
}): JSX.Element {
  if (rows.length === 0) {
    return <div className="text-xs text-slate-500">—</div>;
  }
  const toneClass = tone === "positive" ? "text-emerald-600" : "text-red-600";
  return (
    <ul className="space-y-1 text-sm">
      {rows.map((r) => (
        <li
          key={r.instrument_id}
          className="flex items-baseline justify-between gap-3"
        >
          <Link
            to={`/instrument/${encodeURIComponent(r.symbol)}`}
            className="font-medium text-blue-700 hover:underline"
          >
            {r.symbol}
          </Link>
          <span className={`tabular-nums ${toneClass}`}>
            {formatSignedPnl(r.pnl_delta)}
            {r.pnl_pct !== null ? (
              <span className="ml-2 text-xs">
                ({formatSignedPct(r.pnl_pct)})
              </span>
            ) : null}
          </span>
        </li>
      ))}
    </ul>
  );
}

function ReportList({ reports }: { reports: ReportSnapshot[] }) {
  const [selectedId, setSelectedId] = useState<number | null>(
    reports[0]?.snapshot_id ?? null,
  );
  // Reset selectedId when the list changes and the previous selection is
  // no longer present — otherwise the highlighted button and the detail
  // pane fall out of sync (selected silently falls back to reports[0]).
  useEffect(() => {
    if (reports.length === 0) {
      setSelectedId(null);
      return;
    }
    const present = reports.some((r) => r.snapshot_id === selectedId);
    if (!present) {
      setSelectedId(reports[0]?.snapshot_id ?? null);
    }
  }, [reports, selectedId]);
  const selected = reports.find((r) => r.snapshot_id === selectedId) ?? reports[0];

  return (
    <div className="grid gap-4 md:grid-cols-[200px_1fr]">
      <aside className="border-r border-slate-200 pr-3">
        <ul className="space-y-1 text-sm">
          {reports.map((r) => (
            <li key={r.snapshot_id}>
              <button
                type="button"
                className={`w-full rounded px-2 py-1 text-left ${
                  r.snapshot_id === selected?.snapshot_id
                    ? "bg-slate-200 font-medium"
                    : "hover:bg-slate-100 dark:hover:bg-slate-800"
                }`}
                onClick={() => setSelectedId(r.snapshot_id)}
              >
                {formatDate(r.period_start)} – {formatDate(r.period_end)}
              </button>
            </li>
          ))}
        </ul>
      </aside>
      <div>{selected && <ReportDetail report={selected} />}</div>
    </div>
  );
}

function ReportsTab({ reportType }: { reportType: TabId }) {
  const { data, error, loading } = useAsync<ReportSnapshot[]>(
    () => (reportType === "weekly" ? fetchWeeklyReports() : fetchMonthlyReports()),
    [reportType],
  );

  if (loading) return <SectionSkeleton rows={5} />;
  if (error !== null) return <ErrorView error={error} />;
  if (!data || data.length === 0) {
    return (
      <EmptyState
        title={`No ${reportType} reports yet`}
        description={`${reportType.charAt(0).toUpperCase()}${reportType.slice(1)} reports appear once the ${reportType === "weekly" ? "Monday" : "1st-of-month"} job has run at least once.`}
      />
    );
  }
  return <ReportList reports={data} />;
}

export function ReportsPage() {
  const [activeTab, setActiveTab] = useState<TabId>("weekly");

  return (
    <div className="space-y-4">
      <header className="border-b border-slate-200 pb-2">
        <h1 className="text-xl font-semibold">Reports</h1>
        <p className="text-sm text-slate-500">
          Weekly + monthly performance snapshots from the report jobs.
        </p>
      </header>
      <nav className="flex gap-1 border-b border-slate-200">
        {(["weekly", "monthly"] as TabId[]).map((id) => (
          <button
            key={id}
            type="button"
            className={`px-3 py-2 text-sm ${
              activeTab === id
                ? "border-b-2 border-blue-600 font-medium text-blue-700"
                : "text-slate-500 hover:text-slate-700"
            }`}
            onClick={() => setActiveTab(id)}
          >
            {id.charAt(0).toUpperCase()}
            {id.slice(1)}
          </button>
        ))}
      </nav>
      <Section title={activeTab === "weekly" ? "Weekly snapshots" : "Monthly snapshots"}>
        <ReportsTab reportType={activeTab} />
      </Section>
    </div>
  );
}

export default ReportsPage;
