-- #2157 — index ownership_def14a_observations on source_document_id.
--
-- The rewash's Item 403 arm resolves its instrument set by asking "which
-- instruments already hold rows for this accession?", and reads live
-- observations as well as typed rows so the repair reaches the 41
-- (accession, instrument) pairs whose typed rows an earlier per-instrument
-- rewash already deleted. That lookup filters on source_document_id ALONE —
-- there is no instrument_id to lead with, by construction, since finding the
-- instruments is the point.
--
-- Every existing index leads with instrument_id or holder_name_key
-- (ownership_def14a_observations_pkey, idx_def14a_obs_instrument_period,
-- idx_def14a_obs_instrument_ingested, idx_def14a_obs_holder_period), so the
-- lookup was a sequential scan of 111,867 rows PER ACCESSION and took the
-- full-corpus rewash from ~145 accessions/min to ~28.
--
-- Partitioned table: CREATE INDEX on the parent cascades to every partition
-- and to partitions created later, so no per-partition follow-up is needed.
-- Not CONCURRENTLY — the migration runner wraps each file in a transaction and
-- CREATE INDEX CONCURRENTLY cannot run inside one.
CREATE INDEX IF NOT EXISTS idx_def14a_obs_source_document
    ON ownership_def14a_observations (source_document_id);
