-- #2229 — index ownership_institutions_current on (filer_cik, period_end DESC).
--
-- 13F-HR supersession asks, for each of an instrument's 13F rows, "what is the
-- LATEST period this filer reported for ANY security?" — a later period proves the
-- filer filed again and omitted this one (Form 13F Special Instruction 5b: a
-- holdings report is a COMPLETE statement of the Manager's Section 13(f)
-- holdings).
--
-- The only existing index on this table besides the PK is
-- idx_inst_current_filer (filer_cik), which is not covering: MAX(period_end) then
-- heap-fetches every row for that filer, and a manager like Vanguard holds
-- thousands. Measured on the dev corpus (2.3M rows), the supersession lookup ran
-- 7,651ms for AAPL and 4,025ms for HD. With this index it is 25ms and 17ms — the
-- ownership-rollup endpoint is computed at READ time on every request, so that
-- difference is operator-visible latency, not a batch cost.
--
-- Leading column is filer_cik because the lookup has no instrument_id to lead
-- with, by construction: it is deliberately asking about the filer's holdings in
-- OTHER instruments. period_end DESC makes it an index-only scan for the MAX.
--
-- Not CONCURRENTLY — the migration runner wraps each file in a transaction and
-- CREATE INDEX CONCURRENTLY cannot run inside one.
CREATE INDEX IF NOT EXISTS idx_inst_current_filer_period
    ON ownership_institutions_current (filer_cik, period_end DESC);
